/*
 * generated by Xtext
 */
package org.xtext.example;

import org.eclipse.xtext.parser.antlr.IAntlrParser;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslRuntimeModule extends org.xtext.example.AbstractMyDslRuntimeModule {

	@Override
	public Class<? extends IAntlrParser> bindIAntlrParser() {
		return org.xtext.example.indenting.IndentingParser.class ;
	}
}
